(function(){
  const mod = {
    concepts:[
      {id:'LIQUIDITY_SWEEP', category:'concept', definition:'Price runs a known high or low and closes back inside.', evidence:['wick through prior high/low','close back inside','rejection or volume expansion'], requiredConfirmation:['reclaim','CHOCH or retest'], actionBias:'wait_for_reclaim'},
      {id:'BOS', category:'concept', definition:'Break of structure confirms continuation pressure after a meaningful swing break.', evidence:['close beyond swing','follow-through','retest holds'], requiredConfirmation:['retest acceptance'], actionBias:'continuation_after_retest'},
      {id:'CHOCH', category:'concept', definition:'Change of character shows the prior direction is losing control.', evidence:['opposite swing break','failed continuation','reclaim after sweep'], requiredConfirmation:['follow-through close'], actionBias:'reversal_watch'},
      {id:'SUPPLY_DEMAND', category:'concept', definition:'Zones where aggressive imbalance previously started.', evidence:['displacement from zone','clean base','unmitigated return'], requiredConfirmation:['reaction at zone'], actionBias:'trade_reaction_not_middle'},
      {id:'FVG', category:'concept', definition:'Fair value gap marks imbalance that may attract retest or continuation.', evidence:['three-candle imbalance','price returns into gap','acceptance/rejection'], requiredConfirmation:['close away from gap'], actionBias:'use_as_location'},
      {id:'ORDER_BLOCK', category:'concept', definition:'Last opposing candle before displacement can act as decision zone.', evidence:['displacement after candle','zone not fully mitigated','reaction on retest'], requiredConfirmation:['rejection and structure'], actionBias:'zone_entry_after_proof'},
      {id:'PREMIUM_DISCOUNT', category:'concept', definition:'Range position decides whether long/short location is attractive.', evidence:['range high/low','midpoint','entry relative to equilibrium'], requiredConfirmation:['trade with favorable location'], actionBias:'avoid_poor_location'},
      {id:'COMPRESSION_EXPANSION', category:'concept', definition:'Low range compression often precedes expansion but direction needs proof.', evidence:['shrinking range','low ATR','breakout attempt'], requiredConfirmation:['expansion plus retest'], actionBias:'wait_for_retest'},
      {id:'ACCEPTANCE_REJECTION', category:'concept', definition:'A level matters only after price accepts above/below it or rejects away from it.', evidence:['close beyond level','failed close beyond level','follow-through candle'], requiredConfirmation:['close plus next candle behavior'], actionBias:'judge_level_response'},
      {id:'LIQUIDITY_VOID', category:'concept', definition:'Fast displacement leaves thin trading behind that price may revisit quickly.', evidence:['large body candles','few overlaps','low pullback structure'], requiredConfirmation:['target path not blocked'], actionBias:'use_as_target_or_late_warning'},
      {id:'MITIGATION', category:'concept', definition:'Price returns to a prior imbalance or order block to rebalance before continuation.', evidence:['return to FVG/order block','controlled pullback','reaction in trend direction'], requiredConfirmation:['acceptance/rejection at zone'], actionBias:'continuation_after_mitigation'},
      {id:'FAILED_AUCTION', category:'concept', definition:'Price probes beyond value and quickly fails back into range, trapping breakout traders.', evidence:['breakout wick','close back in range','opposite follow-through'], requiredConfirmation:['failure holds on retest'], actionBias:'trap_reversal'},
      {id:'ROUND_NUMBER_MAGNET', category:'concept', definition:'Large round numbers and option strikes can attract price before reversal or continuation.', evidence:['price stalls near round number','multiple wick reactions','volume cluster'], requiredConfirmation:['reaction away or acceptance through'], actionBias:'avoid_entry_into_magnet'},
      {id:'TIME_OF_DAY_CONTEXT', category:'concept', definition:'The same setup behaves differently during open, midday, news, and close.', evidence:['session phase','volatility regime','time left in session'], requiredConfirmation:['session-appropriate trigger'], actionBias:'adjust_confirmation_by_session'},
      {id:'TARGET_FIRST_THINKING', category:'concept', definition:'A setup is only tradable if a realistic target exists before invalidation cost becomes too large.', evidence:['clean target path','liquidity target','minimum R:R'], requiredConfirmation:['target before entry'], actionBias:'skip_without_target'}
    ]
  };
  if(typeof registerGoldPilotBrainModule === 'function') registerGoldPilotBrainModule('concepts', mod);
  if(typeof module !== 'undefined' && module.exports) module.exports = mod;
})();
